Feature: AG1CP-19: Admitting multiple students

  @Regression @AG1CP-19 @Vlad @AdmittingMultipleStudents
  Scenario Outline: Admitting multiple students
    Given a CTSMS user is logged in to the main page "https://mexil.it/chroma/admin/admin/dashboard"
    When if a student record already exists, the user deletes it:
      | Module              | SubModule   | Class   | Section   | Admission Number   | Alert Text                            | URL                                        |
      | Student Information | Bulk Delete | <Class> | <Section> | <Admission Number> | Are you sure you want to delete this? | https://mexil.it/chroma/student/bulkdelete |
    When user fills in the fields in the "Student Admission" section:
      | Module              | SubModule         | Admission No       | Roll Number   | Class   | Section   | First Name   | Last Name   | Gender   | Date of Birth   | Category   | Email   | Admission Date   | Student Photo   | Blood Group   | As on Date   | Mobile Number   | Height   | Weight   | URL                                    |
      | Student Information | Student Admission | <Admission Number> | <Roll Number> | <Class> | <Section> | <First Name> | <Last Name> | <Gender> | <Date of Birth> | <Category> | <Email> | <Admission Date> | <Student Photo> | <Blood Group> | <As on Date> | <Mobile Number> | <Height> | <Weight> | https://mexil.it/chroma/student/create |
    And user adds a sibling using the "Add Sibling" button:
      | Sibling Class   | Sibling Section   | Sibling First Name   | Sibling Last Name   | Sibling Roll Number   |
      | <Sibling Class> | <Sibling Section> | <Sibling First Name> | <Sibling Last Name> | <Sibling Roll Number> |
    And user adds father's information:
      | Father Name   | Father Phone   | Father Occupation   | Father Photo   |
      | <Father Name> | <Father Phone> | <Father Occupation> | <Father Photo> |
    And user adds mothers's information:
      | Mother Name   | Mother Phone   | Mother Occupation   | Mother Photo   |
      | <Mother Name> | <Mother Phone> | <Mother Occupation> | <Mother Photo> |
    And user adds guardian's information:
      | If Guardian Is   | Guardian Name   | Guardian Relation   | Guardian Email   | Guardian Photo   | Guardian Phone   | Guardian Occupation   | Guardian Address   |
      | <If Guardian Is> | <Guardian Name> | <Guardian Relation> | <Guardian Email> | <Guardian Photo> | <Guardian Phone> | <Guardian Occupation> | <Guardian Address> |
    And user adds information in the "Student Address Details" block:
      | If Guardian Address is Current Address   | Current Address   | If Permanent Address is Current Address   | Permanent Address   |
      | <If Guardian Address is Current Address> | <Current Address> | <If Permanent Address is Current Address> | <Permanent Address> |
    And user adds information in the "Miscellaneous Details" section:
      | Bank Account Number   | Bank Name   | IFSC Code   | National Identification Number   | Local Identification Number   | RTE   | Previous School Details   | Note   |
      | <Bank Account Number> | <Bank Name> | <IFSC Code> | <National Identification Number> | <Local Identification Number> | <RTE> | <Previous School Details> | <Note> |
    And fills out all text fields and uploads files in the "Upload Documents" section:
      | Title #1   | Document #1   | Title #2   | Document #2   | Title #3   | Document #3   | Title #4   | Document #4   |
      | <Title #1> | <Document #1> | <Title #2> | <Document #2> | <Title #3> | <Document #3> | <Title #4> | <Document #4> |
    And saves submission
    And user is searching for a student record based on parameters:
      | Module              | SubModule       | Class   | Section   | Admission Number   | URL                                    |
      | Student Information | Student Details | <Class> | <Section> | <Admission Number> | https://mexil.it/chroma/student/search |
    Then make sure the entry "<Admission Number>" is in the list:
      | Admission Number   | Student Name   | Class(Section)   | Father Name   | Date of Birth   | Gender   | Category   | Mobile Number   | Height   | Weight   | Add Fees |
      | <Admission Number> | <Student Name> | <Class(Section)> | <Father Name> | <Date of Birth> | <Gender> | <Category> | <Mobile Number> | <Height> | <Weight> | $        |
    Then if a student record already exists, the user deletes it:
      | Module              | SubModule   | Class   | Section   | Admission Number   | Alert Text                            | URL                                        |
      | Student Information | Bulk Delete | <Class> | <Section> | <Admission Number> | Are you sure you want to delete this? | https://mexil.it/chroma/student/bulkdelete |
    Examples:
      | Admission Number | Roll Number | Class          | Section               | First Name | Last Name   | Gender | Date of Birth | Category | Email                             | Admission Date | Student Photo     | Blood Group | As on Date | Mobile Number | Height | Weight | Sibling Class | Sibling Section       | Sibling First Name | Sibling Last Name | Sibling Roll Number | Father Name | Father Phone | Father Occupation   | Father Photo     | Mother Name | Mother Phone | Mother Occupation   | Mother Photo     | If Guardian Is | Guardian Name | Guardian Relation | Guardian Phone | Guardian Occupation | Guardian Email                      | Guardian Photo     | Guardian Address | If Guardian Address is Current Address | Current Address                                          | If Permanent Address is Current Address | Permanent Address                                             | Bank Account Number | Bank Name                | IFSC Code     | National Identification Number | Local Identification Number | RTE | Previous School Details      | Note               | Title #1   | Document #1 | Title #2    | Document #2 | Title #3   | Document #3 | Title #4  | Document #4 | Student Name        | Class(Section)              |
      | 42002            | 0002        | SDET           | Cucumber Fundamentals | Anjel      | Doggett     | Female | 01/01/1990    | new      | averill_tibbitshv83@decorating.le | 04/20/2001     | Student_Photo.png | O+          | 11/03/2002 | 6028808881    | 5'1    | 100    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Uniqua      | 602802771    | Father Occupation1  | Father_Photo.png | Princella   | 6028803331   | Mother Occupation1  | Mother_Photo.png | father         | Chroma1       | Tech1             | 6028801021     | Academy1            | antionne_cribbs0@truck.obl          | Guardian_Photo.png | 123 N Street     | true                                   | Textbooks Road 3149, North Hero, Malawi, 525780          | true                                    | Once Street 5488, Shedd, Namibia, 898381                      | 0112345670          | TrustBank                | A123456789010 | 20-10563145-0                  | 1234 4321 1234 4320         | Yes | https://alwaysn0t9jwavvo.vcu | This is a note #1  | Vander #1  | Vander.png  | Medarda #1  | Medarda.png | Victor #1  | Victor.png  | Jayce #1  | Jayce.png   | Anjel Doggett       | SDET(Cucumber Fundamentals) |
      | 42003            | 0003        | SDET           | Cucumber Fundamentals | Shawndale  | Sublett     | Male   | 01/01/1999    | new      | keyon_armentrout0y@practical.ofw  | 04/20/2002     | Student_Photo.png | A+          | 11/03/2003 | 6028808882    | 5'2    | 105    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Naim        | 602802772    | Father Occupation2  | Father_Photo.png | Ayasha      | 6028803332   | Mother Occupation2  | Mother_Photo.png | mother         | Chroma2       | Tech2             | 6028801022     | Academy2            | tyrina_petermangk@complications.jtv | Guardian_Photo.png | 124 N Street     | false                                  | Guard Road 7462, London Mills, France, 077033            | true                                    | Xml Road 6714, Berwick Upon Tweed, Luxembourg, 471628         | 0112345671          | EliteFinance             | A123456789011 | 20-10563145-1                  | 1234 4321 1234 4321         | No  | https://fujitsu6fcj4n.rb     | This is a note #2  | Vander #2  | Vander.png  | Medarda #2  | Medarda.png | Victor #2  | Victor.png  | Jayce #2  | Jayce.png   | Shawndale Sublett   | SDET(Cucumber Fundamentals) |
      | 42004            | 0004        | SDET           | Cucumber Fundamentals | Sandi      | Gerardi     | Female | 01/01/1992    | new      | niomi_sikes0pzg@diane.twl         | 04/20/2003     | Student_Photo.png | B+          | 11/03/2004 | 6028808883    | 5'3    | 110    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Chatoya     | 602802773    | Father Occupation3  | Father_Photo.png | Kady        | 6028803333   | Mother Occupation3  | Mother_Photo.png | other          | Chroma3       | Tech3             | 6028801023     | Academy3            | atara_strohlho@statewide.ah         | Guardian_Photo.png | 125 N Street     | true                                   | Organized Street 6642, Asotin, Gabon, 719769             | false                                   | Stream St 8413, Huntington Beach, Mauritania, 459109          | 0112345672          | Prosperity Alliance Bank | A123456789012 | 20-10563145-2                  | 1234 4321 1234 4322         | Yes | https://displayxvsebkjqo.yn  | This is a note #3  | Vander #3  | Vander.png  | Medarda #3  | Medarda.png | Victor #3  | Victor.png  | Jayce #3  | Jayce.png   | Sandi Gerardi       | SDET(Cucumber Fundamentals) |
      | 42005            | 0005        | SDET           | Cucumber Fundamentals | Darilyn    | Bate        | Male   | 01/01/1993    | new      | emmitt_ishmaelug@angel.saj        | 04/20/2004     | Student_Photo.png | AB+         | 11/03/2005 | 6028808884    | 5'4    | 200    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Kathelyn    | 602802774    | Father Occupation4  | Father_Photo.png | Rana        | 6028803334   | Mother Occupation4  | Mother_Photo.png | father         | Chroma4       | Tech4             | 6028801024     | Academy4            | seanpaul_shislerlc@doc.eej          | Guardian_Photo.png | 126 N Street     | false                                  | Territory Road 2561, State Farm, Ukraine, 571870         | false                                   | Winning St 7008, Joaquin, Antarctica, 917054                  | 0112345673          | Bank of America          | A123456789013 | 20-10563145-3                  | 1234 4321 1234 4323         | No  | https://hydrogen4vp.exk      | This is a note #4  | Vander #4  | Vander.png  | Medarda #4  | Medarda.png | Victor #4  | Victor.png  | Jayce #4  | Jayce.png   | Darilyn Bate        | SDET(Cucumber Fundamentals) |
      | 42006            | 0006        | SDET           | Cucumber Fundamentals | Keirra     | Wimbish     | Female | 01/01/1994    | new      | elizabethann_cappbcuh@yukon.vms   | 04/20/2005     | Student_Photo.png | O-          | 11/03/2006 | 6028808885    | 5'5    | 205    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Kaylah      | 602802775    | Father Occupation5  | Father_Photo.png | Marti       | 6028803335   | Mother Occupation5  | Mother_Photo.png | mother         | Chroma5       | Tech5             | 6028801025     | Academy5            | kyonna_heroldhjhr@shopzilla.lbg     | Guardian_Photo.png | 127 N Street     | true                                   | Seminars St 3054, Alcove, Armenia, 181518                | true                                    | Asia Street 1051, Mount Desert, Costa Rica, 662072            | 0112345674          | TrustBank                | A123456789014 | 20-10563145-4                  | 1234 4321 1234 4324         | Yes | https://arthritiskph.kx      | This is a note #5  | Vander #5  | Vander.png  | Medarda #5  | Medarda.png | Victor #5  | Victor.png  | Jayce #5  | Jayce.png   | Keirra Wimbish      | SDET(Cucumber Fundamentals) |
      | 42007            | 0007        | Cyber Security | API Testing           | Chisholm   | Macias      | Male   | 01/01/1995    | new      | kaitlin_man7i@voltage.doz         | 04/20/2006     | Student_Photo.png | A-          | 11/03/2007 | 6028808886    | 5'6    | 210    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Mashanda    | 602802776    | Father Occupation6  | Father_Photo.png | Vaness      | 6028803336   | Mother Occupation6  | Mother_Photo.png | other          | Chroma6       | Tech6             | 6028801026     | Academy6            | fabien_lapierrem@interesting.vng    | Guardian_Photo.png | 128 N Street     | false                                  | Resorts Street 8621, Crockett Mills, El Salvador, 790896 | true                                    | Administration St 4981, Athol, Netherlands Antilles, 565213   | 0112345675          | Bank of America          | A123456789015 | 20-10563145-5                  | 1234 4321 1234 4325         | No  | https://hostelsye4rs0.yra    | This is a note #6  | Vander #6  | Vander.png  | Medarda #6  | Medarda.png | Victor #6  | Victor.png  | Jayce #6  | Jayce.png   | Chisholm Macias     | Cyber Security(API Testing) |
      | 42008            | 0008        | Cyber Security | API Testing           | Darik      | Blosser     | Female | 01/01/1996    | new      | donna_plumleypm@transport.ps      | 04/20/2007     | Student_Photo.png | B-          | 11/03/2008 | 6028808887    | 5'7    | 300    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Dujuan      | 602802777    | Father Occupation7  | Father_Photo.png | Azure       | 6028803337   | Mother Occupation7  | Mother_Photo.png | father         | Chroma7       | Tech7             | 6028801027     | Academy7            | darcey_mccoinkjn@skilled.zp         | Guardian_Photo.png | 129 N Street     | true                                   | Brass Street 9152, Rishikesh, Solomon Islands, 365522    | false                                   | Sink St 1407, Yangcheng, Mozambique, 877799                   | 0112345676          | Bank of America          | A123456789016 | 20-10563145-6                  | 1234 4321 1234 4326         | Yes | https://yeahuwcbu1n.he       | This is a note #7  | Vander #7  | Vander.png  | Medarda #7  | Medarda.png | Victor #7  | Victor.png  | Jayce #7  | Jayce.png   | Darik Blosser       | Cyber Security(API Testing) |
      | 42009            | 0009        | Cyber Security | API Testing           | Darwin     | Newborn     | Male   | 01/01/1997    | new      | nallely_douglasr7i1@episode.yq    | 04/20/2008     | Student_Photo.png | AB-         | 11/03/2009 | 6028808888    | 5'8    | 305    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Lysandra    | 602802778    | Father Occupation8  | Father_Photo.png | Maegan      | 6028803338   | Mother Occupation8  | Mother_Photo.png | mother         | Chroma8       | Tech8             | 6028801028     | Academy8            | aliah_brunellhjew@mali.ior          | Guardian_Photo.png | 130 N Street     | false                                  | Cologne Street 5921, Lamoine, Tunisia, 994380            | false                                   | Personally St 9297, Lstykke, Northern Mariana Islands, 120262 | 0112345677          | Bank of America          | A123456789017 | 20-10563145-7                  | 1234 4321 1234 4327         | No  | https://nickelr86.tc         | This is a note #8  | Vander #8  | Vander.png  | Medarda #8  | Medarda.png | Victor #8  | Victor.png  | Jayce #8  | Jayce.png   | Darwin Newborn      | Cyber Security(API Testing) |
      | 42010            | 0010        | Cyber Security | API Testing           | Ambor      | Gutowski    | Female | 01/01/1998    | new      | desma_kawamura3gm@sussex.lz       | 04/20/2009     | Student_Photo.png | B+          | 11/03/2010 | 6028808889    | 5'9    | 310    | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Shantal     | 602802779    | Father Occupation9  | Father_Photo.png | Almee       | 6028803339   | Mother Occupation9  | Mother_Photo.png | other          | Chroma9       | Tech9             | 6028801029     | Academy9            | husain_bragdonbd@economy.ioa        | Guardian_Photo.png | 131 N Street     | true                                   | Coupon Street 6881, Whitney Point, Armenia, 144323       | true                                    | Yacht Street 7605, Tsetserleg, Brazil, 563517                 | 0112345678          | TrustBank                | A123456789018 | 20-10563145-8                  | 1234 4321 1234 4328         | Yes | https://packingf.ba          | This is a note #9  | Vander #9  | Vander.png  | Medarda #9  | Medarda.png | Victor #9  | Victor.png  | Jayce #9  | Jayce.png   | Ambor Gutowski      | Cyber Security(API Testing) |
      | 42011            | 0011        | Cyber Security | API Testing           | Mecaela    | Stoneburner | Male   | 01/01/1999    | new      | sumer_lipscombr@football.ct       | 04/20/2010     | Student_Photo.png | B+          | 11/03/2011 | 6028808810    | 6'0    | 0      | SDET          | Cucumber Fundamentals | Vasya              | Petrov            | 1142                | Deantes     | 602802710    | Father Occupation10 | Father_Photo.png | Louie       | 6028803310   | Mother Occupation10 | Mother_Photo.png | father         | Chroma10      | Tech10            | 6028801030     | Academy10           | brittaney_sabo5o@radiation.eg       | Guardian_Photo.png | 132 N Street     | false                                  | Nissan Road 8548, Latah, Swaziland, 183038               | true                                    | Actually St 3459, Moga, Sri Lanka, 866333                     | 0112345679          | TrustBank                | A123456789019 | 20-10563145-9                  | 1234 4321 1234 4329         | No  | https://hdtvpdtnx.awo        | This is a note #10 | Vander #10 | Vander.png  | Medarda #10 | Medarda.png | Victor #10 | Victor.png  | Jayce #10 | Jayce.png   | Mecaela Stoneburner | Cyber Security(API Testing) |