name: Smoke Tests Workflow

on:
  workflow_dispatch:

  workflow_dispatch:
  schedule:
    # During standard time (EST: UTC-5, so set for 5:00 AM UTC)
    - cron: '0 5 * * *'
    # During daylight saving time (EDT: UTC-4, so set for 4:00 AM UTC)
    - cron: '0 4 * * *'

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: github

      - name: Run Tests
        run: mvn -q -Dtest=Run_CTSMS_Smoke_Test test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber-html-report.html