name: Run CTSMS Progression Test and Publish Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run CTSMS Progression Test
        run: mvn test -Dtest=Run_CTSMS_Progression_Test.java -q

      - name: Clean gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .

      - name: Move Cucumber Reports
        run: |
          mkdir docs
          cp -r target/cucumber-reports/* docs/

      - name: Push to GitHub Pages
        run: |
          git config --local user.email "diegojuarezbusiness@gmail.com"
          git config --local user.name "iamdez99"
          git add docs/*
          git commit -m "Update GitHub Pages"
          git push https://${{secrets.GH_PAT}}@github.com/chromatechacademy/Avatars-Group-1.git gh-pages